[project]
name = "i3e-partner"
version = "0.1.0"
description = "A tool"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.2",
    "pytest-playwright>=0.7.0",
    "tinydb>=4.8.2",
]
